# Generated by Django 3.1.2 on 2020-10-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0005_stockhistory_issue_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
